name: Jazzy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install gh-pages
        run:  |
          npm install -g gh-pages
      - name: install jazzy
        run:  |
          gem install jazzy
      - name: create docs
        env:
          GH_Token: ${{ secrets.GH_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run:  |
          git config --global user.name "${USER_NAME}"
          git config --global user.email "${USER_EMAIL}"
          jazzy
          npm run deploy
