name: Jazzy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install jazzy
        run: gem install jazzy
      - name: create docs
        run: jazzy
